networks:
  proxy:
    external: true

services:
  app:
    build: .
    container_name: edx
    restart: unless-stopped
    networks: [proxy]
    labels:
      - traefik.enable=true
      - traefik.http.routers.edx.rule=Host(`edx.edouard.lol`) || Host(`www.edx.edouard.lol`)
      - traefik.http.routers.edx.entrypoints=websecure
      - traefik.http.routers.edx.tls.certresolver=le
      - traefik.http.services.edx.loadbalancer.server.port=80
