name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    uses: 0xEdouard/multi-domain-infra/.github/workflows/reusable-remote-deploy.yml@main
    with:
      stack_name: edx
      remote_compose_path: docker-compose.yml
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
